## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration$time"""
add_newline = true

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[](#8EC07C bold)"
error_symbol = "[](#AD685A)"
vicmd_symbol = "[](#DD8F6E)"

[line_break]
disabled = true


[directory]
format = "[]($style)[ ](bg:#fe8019 fg:#312C2E)[$path](bg:#fe8019 fg:#312C2E bold)[ ]($style)"
style = "bg:none fg:#fe8019"
truncation_length = 3
truncate_to_repo=false

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = "[]($style)[[ ](bg:#8EC07C fg:#312C2E bold)$branch](bg:#8EC07C fg:#312C2E)[ ]($style)"
style = "bg:none fg:#8EC07C"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#689d6a fg:#312C2E)[ ]($style)"
style = "bg:none fg:#689d6a"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

#[nodejs]
#symbol = ""
#style = "bg:#86BBD8"
#format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[神](bg:#928374 fg:#312C2E bold)$duration](bg:#928374 fg:#312C2E)[ ]($style)"
disabled = false
style = "bg:none fg:#928374"

[time]
disabled = false
time_format = "%R" # hour:minute format
style = "bg:none fg:#d79923"
format = "[]($style)[[ ](bg:#d79923 fg:#312C2E bold)$time](bg:#d79923 fg:#312C2E)[ ]($style)"
